# -*- coding: utf-8 -*-
"""femalevsmaleproject5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYwIFo6gk8yypeLWFhYqTBDuqiG2cxsY
"""

import streamlit as st
import numpy as np
from PIL import Image
import joblib

# -------------------------
# Page Configuration
# -------------------------
st.set_page_config(
    page_title="Female vs Male Classifier",
    page_icon="🧑🏽",
    layout="centered"
)

# -------------------------
# Load Model
# -------------------------
model = joblib.load("female_male_model.pkl")

IMG_SIZE = 64

# -------------------------
# Sidebar
# -------------------------
st.sidebar.header("📌 Project Information")
st.sidebar.info(
    """
    **Model:** Logistic Regression
    
    **Input:** Face Image
    
    **Output:** Male / Female
    """
)

st.sidebar.markdown("---")
st.sidebar.markdown("**Made by:** Aditi Srivastava")
st.sidebar.markdown("**Roll No.:** 2401221550005")

# -------------------------
# Main Title
# -------------------------
st.title("🧑🏽👩🏻 Female vs Male Image Classifier")
st.caption("Upload a face image to predict its gender.")

# -------------------------
# Upload Image
# -------------------------
uploaded_file = st.file_uploader(
    "📂 Choose an Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    # Read image using Pillow
    image = Image.open(uploaded_file)

    # Convert to RGB
    image = image.convert("RGB")

    # Display image
    st.image(image, caption="Uploaded Image", width=300)

    # Resize image
    resized = image.resize((IMG_SIZE, IMG_SIZE))

    # Convert to NumPy array
    resized = np.array(resized)

    # Flatten image
    resized = resized.flatten()

    # Prediction
    prediction = model.predict([resized])[0]
    probability = model.predict_proba([resized])[0]

    st.markdown("---")

    # Display prediction
    if prediction == 0:
        st.success("👩🏻 Prediction: FEMALE")
        st.progress(int(probability[0] * 100))
    else:
        st.success("🧑🏽 Prediction: MALE")
        st.progress(int(probability[1] * 100))

    # Display probabilities
    st.subheader("📊 Prediction Confidence")

    col1, col2 = st.columns(2)

    with col1:
        st.metric("👩🏻 Female", f"{probability[0] * 100:.2f}%")

    with col2:
        st.metric("🧑🏽 Male", f"{probability[1] * 100:.2f}%")

st.markdown("---")
st.caption("Made by: Aditi Srivastava | Roll No.: 2401221550005")
